aa: rand-m9-mstd0.5-inc1
advprop: false
advtrain: true
alpha:
- 0.0
- 0.2
- 1.0
alpha_scale_epochs: 9
alpha_scale_init: 0.1
alpha_start_epoch: 0
amp_version: native
apex_amp: false
attack_criterion: trades
attack_domain: pixel
attack_eps: 255.0
attack_it: 3
attack_norm: l1
attack_random_start: true
attack_step: 1.0
attack_use_best: true
aug_repeats: 0
aug_splits: 0
backend: nccl
batch_size: 448
bce_loss: false
bn_eps: null
bn_momentum: null
ce_weight: 0.8
channels_last: false
clip_grad: null
clip_mode: norm
color_jitter: 0
cooldown_epochs: 0
crop_pct: 0.875
cutmix: 1.0
cutmix_minmax: null
decay_epochs: 30
decay_rate: 0.1
device_id: 0
dist_backend: nccl
dist_bn: reduce
dist_url: env://
distributed: false
drop: 0.0
drop_block: null
drop_path: 0.0
epoch_repeats: 0
epochs: 1
eval_dir: /groups/golan_neurogroup/bml_group/datasets/imagenet/val/
eval_metric: top1
experiment_name: null
experiment_num: 1
final_eval: false
final_eval_aa_batch_size: 128
final_eval_aa_completion_csv: autoattack_sweep_results.csv
final_eval_aa_eps: null
final_eval_aa_max_batches: 8
final_eval_aa_norm: null
final_eval_autoattack: true
final_eval_ckpt_name: model_best.pth.tar
final_eval_num_workers: 8
final_eval_out_dir: pgd_eval
final_eval_pgd: true
final_eval_pgd_attack_steps: 10
final_eval_pgd_batch_size: 192
final_eval_pgd_completion_csv: pgd_validation_results.csv
final_eval_pgd_eps: 1,2,4,8,16
final_eval_pgd_max_batches: null
final_eval_pgd_norms: linf,l2,l1
final_eval_plot_x_col: pgd_constrained_eps
final_eval_plots: true
final_eval_require_train_this_run: false
final_eval_skip_if_complete: true
final_eval_val_dir: ''
gp: null
grad_accum: 1
gradnorm: false
gradnorm_max_reg_to_ce_ratio: 1.0
gradnorm_penalty_norm: l1
gradnorm_weight: 1.2
hflip: true
init_method: env://
input_size: 224
interpolation: bicubic
jsd_loss: false
l1_apgd_min_step_scale: 0.01
l1_apgd_rho: 0.05
l1_apgd_use_halving: true
l1_step_mode: l2_norm
layer_decay: null
local_rank: 0
log_interval: 5
loss_fn: DBP
lr: 0.000875
lr_cycle_decay: 0.5
lr_cycle_limit: 1
lr_cycle_mul: 1.0
lr_k_decay: 1.0
lr_noise: null
lr_noise_pct: 0.67
lr_noise_std: 1.0
lrb: 0.001
max_history: 10
mean:
- 0.485
- 0.456
- 0.406
min_lr: 1.0e-05
mixup: 0.8
mixup_active: true
mixup_mode: elem
mixup_off_epoch: 175
mixup_prob: 0.5
mixup_switch_prob: 0.5
model: convnext_small
model_ema: false
model_ema_decay: 0.9998
model_ema_force_cpu: false
model_id: null
momentum: 0.9
native_amp: true
no_aug: false
num_classes: 1000
num_workers: 6
opt: adamw
opt_betas: null
opt_eps: 1.0e-08
output_dir: /home/ashtomer/projects/ares/outs/timing_testing/slurm_baselines/rtx_pro_6000/pixel_l1_trades_rs_on/bsz_448_nw_6/pixel_l1_trades_rs_on/baseline/bsz_448/convnext_small_l1trades_2_init1
patience_epochs: 0
pin_mem: true
random_start: true
random_start_eps_factor: 0.5
rank: 0
ratio:
- 0.75
- 1.3333
recount: 1
recovery_interval: 0
remode: pixel
reprob: 0
resplit: false
resume: ''
save_log: save_log.txt
scale:
- 0.08
- 1.0
sched: cosine
sched_on_updates: true
seed: 0
smoothing: 0.1
split_bn: false
start_epoch: null
std:
- 0.229
- 0.224
- 0.225
sync_bn: false
trades_beta: 1.0
trades_random_start_override: true
train_dir: /groups/golan_neurogroup/bml_group/datasets/imagenet/train/
train_interpolation: bicubic
v1_attack_eps: 1.0
v1_attack_it: 3
v1_attack_random_start: false
v1_attack_step: null
v1_attack_use_best: true
vflip: false
warmup_epochs: 20
warmup_lr: 1.0e-06
weight_decay: 0.05
world_size: 1
